### ISSUE TITLE
ZeroConf finds no services

### ISSUE THREAD

**Issue by y-lohse** [vstirbu/ZeroConf#6]
Hi, I'm trying to use this plugin but I can't get it to discover any service. 
The console shows the `Watch _calbr-wsgui._tcp.local.` message but the callback is never fired. I can see the services using another app from the same device. My app has ACCESS_WIFI_STATE & CHANGE_WIFI_MULTICAST_STATE permissions.
Any idea of what could cause thee problem?

**Comment by cleverplatypus** [comment]
Hi, I had the same problem with the plugin not being able to list services advertised by another device using the same plugin.
A bit of logging revealed that the `getIPAddress` function was always returning `null` because no IPv4 address was ever found.

I changed the method to the following and it now works.
```java
//Additional imports
import java.net.Inet4Address;
import java.util.Enumeration;


public static InetAddress getIPAddress() {
    try { 
        for (Enumeration<NetworkInterface> en = NetworkInterface.getNetworkInterfaces(); en.hasMoreElements();) { 
            NetworkInterface intf = en.nextElement();
            for (Enumeration<InetAddress> enumIpAddr = intf.getInetAddresses(); enumIpAddr.hasMoreElements();) { 
                InetAddress inetAddress = enumIpAddr.nextElement(); 
                if (!inetAddress.isLoopbackAddress()) { 
                    if (inetAddress instanceof Inet4Address) {
                       return inetAddress;
                    } 
                } 
            } 
        } 
    } catch (Exception ex) { 
        Log.e("ZeroConf", "getIPAddress()", ex); 
    } 
    return null; 
}
```
There is still the caveat that the method always returns the first useful IP it finds, which might not be the right one for the use case, but there you go...
